PathToLinux="C:/Users/ABMARATH/Documents/Work/PatchTracker/linux"
PathToBionic="C:/Users/ABMARATH/Documents/Work/PatchTracker/linux"
PathToClone="C:/Users/ABMARATH/Documents/Work/PatchTracker/"
PathToCommitLog="C:/Users/ABMARATH/Documents/Work/PatchTracker/commit-log"
PathToLastsha="C:/Users/ABMARATH/Documents/Work/PatchTracker/lastSHA"
NameMaintainers="MAINTAINERS"