PathToLinux="C:/Users/ABMARATH/Documents/Work/PatchTracker/linux"
PathToCloneLinux="C:/Users/ABMARATH/Documents/Work/PatchTracker/"
PathToCommitLog="C:/Users/ABMARATH/Documents/Work/PatchTracker/commit-log"
PathToLastsha="C:/Users/ABMARATH/Documents/Work/PatchTracker/lastSHA"
NameMaintainers="MAINTAINERS"